### ISSUE TITLE
Semantics of get() on cache miss

### ISSUE THREAD

**Issue by jsor** [reactphp/cache#13]
Currently, `get()` returns a rejected promise on a cache miss. Since rejection is the asynchronous equivalent of throwing an exception in synchronous code, it behaves like

```php
public function get($key)
{
    if (!isset($this->data[$key])) {
        throw new \Exception()
    }

    return $this->data[$key];
}
```

Is this the intended behavior?

**Comment by WyriHaximus** [comment]
What would you expect in this situation @jsor? That behavior makes perfect sense to me, and I'm using it extensively for flow control in applications/packages.

**Comment by jsor** [comment]
The *correct* implementation in ArrayCache would be:

```
public function get($key)
{
    if (!isset($this->data[$key])) {
        return Promise\resolve(null);
    }

    return Promise\resolve($this->data[$key]);
}
```

Rejection means that an error occured, eg. in the underlying storage system.

In case of the [WyriHaximus/reactphp-cache-redis](https://github.com/WyriHaximus/reactphp-cache-redis/blob/master/src/Redis.php#L37) implementation, rejection should only happen when the redis client reports an error, eg. https://github.com/clue/php-redis-react/blob/master/src/StreamingClient.php#L90 because this is then a bug in your application.

The implementation should be something like

```php
public function get($key)
{
    return $this->client->exists($this->prefix . $key)->then(function ($result) use ($key) {
        if ($result == false) {
            return null;
        }

        return $this->client->get($this->prefix . $key);
    });
}
```

And used like

```php
$redisCache->get('foo')->then(
    function ($result) {
        if (null ==== $result) {
            // cache miss
            return createAndStoreAndReturn('foo');
        }

        return handle($result);
    },
    function (\Exception $e) {
        call('WyriHaximus')->andTellHim('Theres a bug in your application or the redis server is down');
    }
);
```

**Comment by kelunik** [comment]
+1 for returning `null` on miss. Works well with `??`.

**Comment by jsor** [comment]
An alternative approach would be to reject with an exception on cache miss. This way, a cache miss can be handled differently than exceptions thrown from the underlying storage system (requires react/promise ^2.0).

```php
$cache->get('foo')
    ->otherwise(function (CacheMissException $e) {
        return getFromDB('foo');
    })
    ->otherwise(function($e) {
        log($e);
    })
    ->then('var_dump');
;
```

**Comment by kelunik** [comment]
@jsor If a cache miss returns `null` and an issue in the underlying storage system throws an exception you can differentiate that as well. And you don't have exceptions for non-exceptional code paths.

**Comment by jsor** [comment]
@kelunik You don't have to convience me, i've opened that issue ;)

**Comment by clue** [comment]
I agree that returning `null` makes sense here as this clearly isn't "exceptional" :+1:

**Comment by WyriHaximus** [comment]
Work in Progress PR up at #22
