### ISSUE TITLE
Return values for set and remove

### ISSUE THREAD

**Issue by maciejmrozinski** [reactphp/cache#15]
As shortly discussed [here](https://github.com/WyriHaximus/reactphp-cache-redis/pull/2) we're considering to return `PromiseInterface` for `set` and `remove` methods. Do You have any reasons to not agree?

**Comment by jsor** [comment]
Definitely +1

**Comment by clue** [comment]
Yeah, makes perfect sense :+1:

**Comment by maciejmrozinski** [comment]
#16
