### ISSUE TITLE
Limit cache size for ArrayCache

### ISSUE THREAD

**Issue by clue** [reactphp/cache#17]
The `ArrayCache` keeps growing and growing when new data is added to it. We should probably add an optional parameter to limit the cache size and implement a simple LRU algorithm to remove "old" entries.

**Comment by WyriHaximus** [comment]
When would we run the algorithm to clean up? Maybe we could go with FIFO instead which could be simpler. `ArrayCache` should be replaced with another implementation in larger apps honestly: https://github.com/reactphp/react/wiki/Users#cache-implementations (we could use more tbh)

**Comment by clue** [comment]
> When would we run the algorithm to clean up? Maybe we could go with FIFO instead which could be simpler.

"LRU algorithm" may sound more complicated than it actually is :-) This essentially means you keep track of the entries that were last accessed and simply remove the oldest one once adding a new entry to the cache.

> `ArrayCache` should be replaced with another implementation in larger apps honestly: https://github.com/reactphp/react/wiki/Users#cache-implementations (we could use more tbh)

No objections, I think this mostly boils down to good documentation though :+1: I think having `ArrayCache` as a default makes sense for most use cases, but we should probably prominently suggest using alternative implementations for the more specialized use cases :+1:
