### ISSUE TITLE
[RFC] Prepare stable release

### ISSUE THREAD

**Issue by clue** [reactphp/cache#8]
We should look into providing a stable (in the sense of SemVer) release for this component.

From looking at the version history it looks like the very first tagged release could in fact already have been a v1.0.0.

This ticket aims to serve as an RFC.

**Comment by clue** [comment]
IMO there's no reason we should not aim for a v1.0.0 tag soon.

Though personally I'd like to get in #7 first, as it literally requires no code modification whatsoever.

**Comment by WyriHaximus** [comment]
Sounds good to me :+1:

**Comment by clue** [comment]
FWIW, the only public package that depends on this is currently our DNS component: https://packagist.org/packages/react/cache/dependents

All PRs are in now, let's look into getting a stable release out :shipit:

**Comment by clue** [comment]
Resolved via https://github.com/reactphp/cache/commit/aa10d63a1b40a36a486bdf527f28bac607ee6466 :shipit: :tada:
